---
abstract: 'find nearest neighbor for a set of points'
author:
  - 'Salvador Fandino <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Vector-Real-Neighbors
no_index:
  directory:
    - t
    - inc
requires:
  Math::Vector::Real: '0.14'
  Math::Vector::Real::kdTree: '0.11'
  Sort::Key::Radix: '0.13'
version: '0.02'
