--- #YAML:1.0
name:               Math-Vector-Real-Neighbors
version:            0.01
abstract:           find nearest neighbor for a set of points
author:
    - Salvador Fandino <sfandino@yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::Vector::Real:  0.04
    Sort::Key::Radix:    0.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
